#!/bin/sh

set -e

DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

HOST=$1

if [ -z "$HOST" ]; then
  echo "No host provided"
  exit 1
fi

read -p "Enter space-delimited users ($(./cmd/get-users)): " users

if [ "$users" ]; then
  ./cmd/set-users $users
fi

if [[ "$(uname -s)" == Darwin* ]]; then
  exec ./cmd/mac-install $HOST
fi
