#!/bin/sh

HOST=$1

if [ ! "$HOST" ]; then
  fail "No host provided"
fi

HOST_DIR="$REPO_ROOT/hosts/$HOST"

if [ ! -d "$HOST_DIR" ]; then
  mkdir -p $HOST_DIR
fi

DEFAULT_FILE="$HOST_DIR/default.nix"
DOTCONFIG_FILE="$HOST_DIR/.config.nix"

if [ ! -f "$DEFAULT_FILE" ]; then
cat << EOF > $DEFAULT_FILE
{ inputs, ... }:

inputs.<INPUT>.lib.<OS>System { # TODO
  system = ""; # TODO
  specialArgs = { inherit inputs; };
  modules = [
    # inputs.nixos-hardware.nixosModules.<HARDWARE> # TODO
    ../../modules/common
    # ../../modules/macos # TODO
    # ../../modules/nixos # TODO
    ./.config.nix
    {
      # TODO
    }
  ];
}
EOF
fi
