#!/bin/sh

HOST=$1

if [ ! "$HOST" ]; then
  fail "No host provided"
fi

HOST_DIR="$REPO_ROOT/hosts/$HOST"

if [ ! -d "$HOST_DIR" ]; then
  mkdir -p $HOST_DIR
fi

HWCONFIG_FILE="$HOST_DIR/hardware.nix"

sudo nixos-generate-config --no-filesystems --show-hardware-config > $HWCONFIG_FILE
