#!/bin/sh

NIX="/nix/var/nix/profiles/default/bin/nix"

HOST=$1

if [ ! "$HOST" ]; then
  fail "No host provided"
fi

if [ ! "$($NIX --version)" ]; then
  curl --proto '=https' --tlsv1.2 -sSf -L \
  https://install.determinate.systems/nix | sh -s -- install
fi

$NIX run nix-darwin switch --flake "$REPO_ROOT#$HOST"

sudo reboot
