#!/bin/bash

set -e

DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

NIX=/nix/var/nix/profiles/default/bin/nix

if [ ! -e ~/.config/nix ]; then
  mkdir -p ~/.config

  ln -s $DIR/.config/nix ~/.config/nix
fi

if ! command -v $NIX 2>&1 >/dev/null; then
  curl -L https://nixos.org/nix/install | sh
fi

$NIX run nix-darwin -- switch --flake .#$1

sudo reboot
