#!/bin/sh

HOST=$1

if [ ! "$HOST" ]; then
  fail "No host provided"
fi

HOST_DIR="$REPO_ROOT/hosts/$HOST"

if [ ! -d "$HOST_DIR" ]; then
  mkdir -p $HOST_DIR
fi

PASSWD_FILE="$HOST_DIR/.passwd.nix"
PASSWD=$(mkpasswd)

cat << EOF > $PASSWD_FILE
{
  user.hashedPassword = "$PASSWD";
}
EOF

git add --intent-to-add $PASSWD_FILE
git update-index --assume-unchanged $PASSWD_FILE

chmod 600 $PASSWD_FILE