#!/bin/bash

set -e

DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

USERS_FILE=$DIR/../config/users.nix

if [ $# -lt 1 ]; then
  echo "[]" > $USERS_FILE
else
  echo "[ $(echo "$@" | sed 's| |" "|g; s|.*|"&"|') ]" > $USERS_FILE
fi

git add --intent-to-add $USERS_FILE
git update-index --assume-unchanged $USERS_FILE
