{
  imports = [
    ./activitywatch.nix
    ./bitwarden.nix
    ./brave.nix
    ./chrome.nix
    ./chromium.nix
    ./discord.nix
    ./firefox.nix
    ./keepassxc.nix
    ./ledger-live.nix
    ./mattermost.nix
    ./slack.nix
    ./spotify.nix
    ./steam.nix
    ./telegram.nix
    ./t3code.nix
    ./zoom.nix
  ];
}
